wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.11
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1695514897.538324
    t:
      1:
      - 2
      - 3
      - 12
      - 45
      - 55
      2:
      - 2
      - 3
      - 12
      - 45
      - 55
      3:
      - 23
      4: 3.10.12
      5: 0.15.11
      8:
      - 5
      13: linux-x86_64
'?':
  desc: null
  value: false
alsologtostderr:
  desc: null
  value: false
batch_size:
  desc: null
  value: 256
chex_assert_multiple_cpu_devices:
  desc: null
  value: false
chex_n_cpu_devices:
  desc: null
  value: 1
chex_skip_pmap_variant_if_single_device:
  desc: null
  value: true
config:
  desc: null
  value: 'actor_lr: 0.0003

    critic_lr: 0.0003

    discount: 0.99

    model_cls: ScoreMatchingLearner

    num_qs: 2

    tau: 0.005

    '
delta_threshold:
  desc: null
  value: 0.5
env_name:
  desc: null
  value: walker_walk
eval_episodes:
  desc: null
  value: 1
eval_interval:
  desc: null
  value: 10000
hbm_oom_exit:
  desc: null
  value: true
help:
  desc: null
  value: false
helpfull:
  desc: null
  value: false
helpshort:
  desc: null
  value: false
helpxml:
  desc: null
  value: false
log_dir:
  desc: null
  value: ''
log_interval:
  desc: null
  value: 1000
logger_levels:
  desc: null
  value: {}
logtostderr:
  desc: null
  value: false
max_steps:
  desc: null
  value: 1000000
only_check_args:
  desc: null
  value: false
op_conversion_fallback_to_while_loop:
  desc: null
  value: true
pdb:
  desc: null
  value: false
pdb_post_mortem:
  desc: null
  value: false
profile_file:
  desc: null
  value: null
project_name:
  desc: null
  value: jaxrl5_online
run_with_pdb:
  desc: null
  value: false
run_with_profiling:
  desc: null
  value: false
runtime_oom_exit:
  desc: null
  value: true
save_video:
  desc: null
  value: true
seed:
  desc: null
  value: 42
showprefixforinfo:
  desc: null
  value: true
start_training:
  desc: null
  value: 10000
stderrthreshold:
  desc: null
  value: fatal
test_random_seed:
  desc: null
  value: 301
test_randomize_ordering_seed:
  desc: null
  value: ''
test_srcdir:
  desc: null
  value: ''
test_tmpdir:
  desc: null
  value: /tmp/absl_testing
tqdm:
  desc: null
  value: true
tt_check_filter:
  desc: null
  value: false
tt_single_core_summaries:
  desc: null
  value: false
use_cprofile_for_profiling:
  desc: null
  value: true
utd_ratio:
  desc: null
  value: 1
v:
  desc: null
  value: 0
verbosity:
  desc: null
  value: 0
wandb:
  desc: null
  value: true
xml_output_file:
  desc: null
  value: ''
